title: vmtk - the Vascular Modelling Toolkit
vmtkversion: "x.xx.x"
devvmtkversion: "x.xx.x-xx"
vmtk_maindownload_unix: ""
vmtk_maindownload_windows: ""
baseurl: ""
# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
  provider : disqus
  disqus :
    short_name : vmtk